import React from 'react'
import './App.css'

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>Welcome to Your App</h1>
        <p>Generated by TaskForge AI Team</p>
      </header>
      <main>
        <p>Your AI-generated components will appear here.</p>
      </main>
    </div>
  )
}

export default App